# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

name: $(Build.BuildId)_$(Date:yyyy-MM-dd).$(Rev:r)

pr: 
   branches:
     include:
       - master
pool:
  vmImage: 'macos-latest'
stages:
- stage: stage1
  displayName: First stage for Android
  jobs:
  - job: Trigger_Build
    displayName: Job1 for build
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'assembleDebug test'
      displayName: gradlew assembleDebug testx

    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'Android Service Connection'
        appSlug: 'krkeshavray/andriod-app'
        appFile: '**/app-prod-debug.apk'
        symbolsOption: 'Android'
        releaseNotesOption: 'input'
        releaseNotesInput: 'Release notes'
        destinationType: 'groups'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
      displayName: Copy .apk files to artifact staging directory
    - task: GithubRelease@0 
      displayName: 'Create GitHub Release'      
      inputs:
       gitHubConnection: keshavray
       repositoryName: keshavray/pipelines-android
       tagSource: manual
       tag: $(Build.BuildNumber)  
   
    
