# Android

# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

name: $(Build.BuildId)_$(Date:yyyy-MM-dd).$(Rev:r)
variables:
- name: myVar
pr: 
   branches:
     include:
       - master
pool:
  vmImage: 'Ubuntu-latest'
stages:
- stage: stage1
  displayName: First stage for Android
  jobs:
  - job: Trigger_Build
    displayName: Job1 for build
    steps:


    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          version=$(grep "versionName" ./app/build.gradle | sed -n '1p' | awk -F'"' '$0=$2')          
          echo $version  
          echo "##vso[task.setVariable variable=version]$version"
      
    - task: GithubRelease@0 
      displayName: 'Create GitHub Release'      
      inputs:
       gitHubConnection: github.com_keshavray
       repositoryName: keshavray/pipelines-android
       tagSource: manual
       tag: "Dev-$(version)" 